"""empty message

Revision ID: 498fbebabb1e
Revises: a944193aec64
Create Date: 2022-02-12 23:35:55.742312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498fbebabb1e'
down_revision = 'a944193aec64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reservation', sa.Column('end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reservation', 'end_time')
    # ### end Alembic commands ###
