"""empty message

Revision ID: 718ca9646dd2
Revises: 
Create Date: 2022-02-17 20:21:02.006767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718ca9646dd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Driver',
    sa.Column('oauth_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('profile_photo', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequent_charger', sa.Boolean(), nullable=True),
    sa.Column('total_kwh_consumed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Provider',
    sa.Column('oauth_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('profile_photo', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('kwh_provided', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('plug_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['Driver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Charger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('charger_type', sa.String(length=20), nullable=True),
    sa.Column('location_longitude', sa.String(length=100), nullable=True),
    sa.Column('location_latitude', sa.String(length=100), nullable=True),
    sa.Column('plug_type', sa.String(length=20), nullable=True),
    sa.Column('covered_parking', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['Provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('charger_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['Car.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['charger_id'], ['Charger.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['Driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reservation')
    op.drop_table('Charger')
    op.drop_table('Car')
    op.drop_table('Provider')
    op.drop_table('Driver')
    # ### end Alembic commands ###
