"""empty message

Revision ID: 74adb668e3a7
Revises: 27465d36700d
Create Date: 2019-10-03 08:12:56.297921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74adb668e3a7'
down_revision = '27465d36700d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('show', sa.Column('id', sa.Integer(), nullable=False))
    op.execute("ALTER TABLE show ADD COLUMN id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT;")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'id')
    # ### end Alembic commands ###
