"""empty message

Revision ID: 7c0b82c101c2
Revises: ebd513946b44
Create Date: 2022-02-09 20:26:32.975027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0b82c101c2'
down_revision = 'ebd513946b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Charger', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Charger', 'Provider', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Charger', type_='foreignkey')
    op.drop_column('Charger', 'provider_id')
    # ### end Alembic commands ###
