"""empty message

Revision ID: bd94371ade7f
Revises: 36672365c501
Create Date: 2022-02-13 14:24:46.025884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd94371ade7f'
down_revision = '36672365c501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Reservation_car_id_fkey', 'Reservation', type_='foreignkey')
    op.drop_constraint('Reservation_charger_id_fkey', 'Reservation', type_='foreignkey')
    op.drop_constraint('Reservation_driver_id_fkey', 'Reservation', type_='foreignkey')
    op.create_foreign_key(None, 'Reservation', 'Car', ['car_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Reservation', 'Driver', ['driver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Reservation', 'Charger', ['charger_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Reservation', type_='foreignkey')
    op.drop_constraint(None, 'Reservation', type_='foreignkey')
    op.drop_constraint(None, 'Reservation', type_='foreignkey')
    op.create_foreign_key('Reservation_driver_id_fkey', 'Reservation', 'Driver', ['driver_id'], ['id'])
    op.create_foreign_key('Reservation_charger_id_fkey', 'Reservation', 'Charger', ['charger_id'], ['id'])
    op.create_foreign_key('Reservation_car_id_fkey', 'Reservation', 'Car', ['car_id'], ['id'])
    # ### end Alembic commands ###
