"""empty message

Revision ID: ddff0fac4b35
Revises: 7c0b82c101c2
Create Date: 2022-02-09 21:24:04.499683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddff0fac4b35'
down_revision = '7c0b82c101c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Charger', sa.Column('location_longitude', sa.String(length=100), nullable=True))
    op.add_column('Charger', sa.Column('location_latitude', sa.String(length=100), nullable=True))
    op.drop_column('Charger', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Charger', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('Charger', 'location_latitude')
    op.drop_column('Charger', 'location_longitude')
    # ### end Alembic commands ###
